language = "C"
include_version = true
include_guard = "RUST_DYNAMIPS_C_H"
pragma_once = true
documentation_style = "c++"
style = "tag"
sys_includes = [
    "pthread.h",
    "setjmp.h",
    "stdio.h",
    "sys/uio.h",
    "sys/un.h",
]
after_includes = """
#if defined(GEN_ETH)
#include <pcap.h>
#endif

#define _attribute_aligned(n) __attribute__ ((aligned(n)))

// cbindgen 0.27.0 assumes unknown types are opaque typedefs, but some C types need struct
typedef struct sockaddr sockaddr;
typedef struct sockaddr_un sockaddr_un;

// forward declarations to avoid the warning: ‘struct’ declared inside parameter list will not be visible outside of this definition or declaration
// see https://stackoverflow.com/a/16831951
struct vdevice;

// cbindgen 0.27.0 puts the typedef of a struct after the struct declaration,
// so structs that use that typedef internally need a forward declaration of the typedef
typedef struct c3600_router c3600_t;
typedef struct c7200_router c7200_t;
typedef struct cpu_gen cpu_gen_t;
typedef struct cpu_group cpu_group_t;
typedef struct cpu_mips cpu_mips_t;
typedef struct cpu_ppc cpu_ppc_t;
typedef struct cpu_tb cpu_tb_t;
typedef struct cpu_tc cpu_tc_t;
typedef struct fs_nvram fs_nvram_t;
typedef struct hash_node hash_node_t;
typedef struct hash_table hash_table_t;
typedef struct insn_exec_page insn_exec_page_t;
typedef struct m_list m_list_t;
typedef struct memblock memblock_t;
typedef struct mempool mempool_t;
typedef struct netio_desc netio_desc_t;
typedef struct netio_fifo_desc netio_fifo_desc_t;
typedef struct netio_fifo_pkt netio_fifo_pkt_t;
typedef struct netio_pktfilter netio_pktfilter_t;
typedef struct parser_context parser_context_t;
typedef struct parser_token parser_token_t;
typedef struct ppc32_jit_tcb ppc32_jit_tcb_t;
typedef struct rbtree_node rbtree_node;
typedef struct rbtree_tree rbtree_tree;
typedef struct registry registry_t;
typedef struct registry_entry registry_entry_t;
typedef struct timer_entry timer_entry_t;
typedef struct timer_queue timer_queue_t;
typedef struct virtual_tty vtty_t;
typedef struct vm_chunk vm_chunk_t;
typedef struct vm_ghost_image vm_ghost_image_t;
typedef struct vm_instance vm_instance_t;
#if !defined(USE_UNSTABLE)
typedef struct mips64_jit_tcb mips64_jit_tcb_t;
#endif

// volatile types (cbindgen does not emit the C volatile type qualifier)
typedef timer_entry_t *volatile Volatile_____timer_entry_t;
typedef volatile int Volatile_c_int;
typedef volatile unsigned int Volatile_m_uint32_t;
typedef volatile unsigned int Volatile_u_int;
typedef volatile unsigned long long Volatile_m_uint64_t;
"""

[defines]
"feature = ENABLE_GEN_ETH" = "GEN_ETH" # has optional dependencies of gen_eth
"feature = ENABLE_LINUX_ETH" = "LINUX_ETH" # has optional dependencies of linux_eth
"feature = USE_DEBUG_BLOCK_TIMESTAMP" = "USE_DEBUG_BLOCK_TIMESTAMP" # some struct fields only exist with DEBUG_BLOCK_TIMESTAMP
"feature = USE_DEBUG_SYM_TREE" = "USE_DEBUG_SYM_TREE" # a match case only exists with DEBUG_SYM_TREE
"feature = USE_MIPS64_AMD64_TRANS" = "USE_MIPS64_AMD64_TRANS" # translate mips64 executable code to x86_64 machine code
"feature = USE_MIPS64_NOJIT_TRANS" = "USE_MIPS64_NOJIT_TRANS" # do not translate mips64 executable code
"feature = USE_MIPS64_PPC32_TRANS" = "USE_MIPS64_PPC32_TRANS" # translate mips64 executable code to powerpc machine code
"feature = USE_MIPS64_X86_TRANS" = "USE_MIPS64_X86_TRANS" # translate mips64 executable code to x86 machine code
"feature = USE_PPC32_AMD64_TRANS" = "USE_PPC32_AMD64_TRANS" # translate ppc32 executable code to x86_64 machine code
"feature = USE_PPC32_NOJIT_TRANS" = "USE_PPC32_NOJIT_TRANS" # do not translate ppc32 executable code
"feature = USE_PPC32_X86_TRANS" = "USE_PPC32_X86_TRANS" # translate ppc32 executable code to x86 machine code
"feature = USE_UNSTABLE" = "USE_UNSTABLE" # some code is different in unstable
"if_0" = "XXX_NOT_SUPPORTED"
"target_arch = x86_64" = "HAS_TARGET_ARCH_X86_64"
"target_arch = x86" = "HAS_TARGET_ARCH_X86"
"target_endian = big" = "HAS_TARGET_ENDIAN_BIG"
"target_endian = little" = "HAS_TARGET_ENDIAN_LITTLE"

[export]
exclude = [
    "JIT_SUPPORT", # symbol appears multiple times
]

[layout]
aligned_n = "_attribute_aligned"
packed = "__attribute__ ((__packed__))"
