# iOS CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    macos:
      xcode: "12.5.1"

    steps:
      - checkout

      - run:
          name: Set timezone and check current datetime
          command: |
            sudo systemsetup -settimezone Europe/Warsaw
            echo "Today is $(date +"%Y-%m-%d %T")"
            echo 'export HOMEBREW_NO_AUTO_UPDATE=1' >> ~/.envs

      - run:
          name: Install libelf
          command: |
            source ~/.envs
            brew install libelf

      - run:
          name: Install cmake
          command: |
            source ~/.envs
            brew install cmake

      - run:
          name: Build dynamips
          command: |
            mkdir build
            cd build
            cmake ..
            make
            cd ..

      - run:
          name: Gather artifacts
          command: |
            mkdir artifacts
            mv build/unstable/dynamips artifacts/dynamips-unstable-osx

      - store_artifacts:
          path: artifacts
          destination: artifacts

      - run:
          name: Upload nightly builds to SF
          command: |
            if [ -n "${RUN_NIGHTLY_BUILD}" ]; then
              ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
              echo "mkdir \"/home/frs/project/gns-3/Nightly Builds/$(date +"%Y-%m-%d")/\"" | sftp gns3build@frs.sourceforge.net
              echo -ne "
                cd \"/home/frs/project/gns-3/Nightly Builds/$(date +"%Y-%m-%d")/\"
                put \"artifacts/dynamips-unstable-osx\"
              " | sftp gns3build@frs.sourceforge.net
            fi

