language = "C"
include_version = true
include_guard = "RUST_DYNAMIPS_C_H"
pragma_once = true
documentation_style = "c++"
style = "tag"
sys_includes = ["pthread.h","setjmp.h","sys/un.h"]
after_includes = """

// forward declarations (cbindgen places typedefs after the struct definitions, preventing you from using them in the structs)
typedef struct cbm_array cbm_array_t;
typedef struct cpu_gen cpu_gen_t;
typedef struct cpu_group cpu_group_t;
typedef struct cpu_mips cpu_mips_t;
typedef struct cpu_ppc cpu_ppc_t;
typedef struct fd_pool fd_pool_t;
typedef struct fs_nvram fs_nvram_t;
typedef struct hash_node hash_node_t;
typedef struct hash_table hash_table_t;
typedef struct insn_lookup insn_lookup_t;
typedef struct jit_op jit_op_t;
typedef struct jit_op_data jit_op_data_t;
typedef struct memblock memblock_t;
typedef struct mempool mempool_t;
typedef struct mips_cp0 mips_cp0_t;
typedef struct mips_cp1 mips_cp1_t;
typedef struct netio_desc netio_desc_t;
typedef struct netio_fifo_desc netio_fifo_desc_t;
typedef struct netio_fifo_pkt netio_fifo_pkt_t;
typedef struct netio_geneth_desc netio_geneth_desc_t;
typedef struct netio_inet_desc netio_inet_desc_t;
typedef struct netio_lnxeth_desc netio_lnxeth_desc_t;
typedef struct netio_pktfilter netio_pktfilter_t;
typedef struct netio_stat netio_stat_t;
typedef struct netio_tap_desc netio_tap_desc_t;
typedef struct netio_unix_desc netio_unix_desc_t;
typedef struct netio_vde_desc netio_vde_desc_t;
typedef struct parser_context parser_context_t;
typedef struct parser_token parser_token_t;
typedef struct ptask ptask_t;
typedef struct rbtree_node rbtree_node;
typedef struct rbtree_tree rbtree_tree;
typedef struct registry registry_t;
typedef struct registry_entry registry_entry_t;
typedef struct rfc_array rfc_array_t;
typedef struct rfc_eqclass rfc_eqclass_t;
typedef struct sockaddr sockaddr;
typedef struct sockaddr_un sockaddr_un;
typedef struct timer_entry timer_entry_t;
typedef struct timer_queue timer_queue_t;
typedef struct tlb_entry tlb_entry_t;
typedef struct virtual_tty vtty_t;
typedef struct vm_chunk vm_chunk_t;
typedef struct vm_instance vm_instance_t;
typedef struct vm_obj vm_obj_t;
typedef struct vm_platform vm_platform_t;

typedef int (*timer_proc)(void *arg1, timer_entry_t *arg2);

// volatile types (cbindgen does not emit the C volatile type qualifier)
typedef timer_entry_t *volatile Volatile_____timer_entry_t;
typedef volatile int Volatile_c_int;
typedef unsigned int m_uint32_t;
typedef unsigned long long m_uint64_t;
typedef volatile m_uint32_t Volatile_m_uint32_t;
typedef volatile m_uint64_t Volatile_m_uint64_t;
typedef volatile u_int Volatile_u_int;

// Host CPU Types
#define CPU_x86    0
#define CPU_amd64  1
#define CPU_nojit  2

// Number of host registers available for JIT
#if JIT_CPU == CPU_x86
#define JIT_HOST_NREG  8
#elif JIT_CPU == CPU_amd64
#define JIT_HOST_NREG  16
#else
#define JIT_HOST_NREG  0
#endif
"""

[defines]
"feature = USE_UNSTABLE" = "USE_UNSTABLE"
"feature = ENABLE_LINUX_ETH" = "LINUX_ETH"
"feature = ENABLE_GEN_ETH" = "GEN_ETH"

[layout]
packed = "__attribute__ ((__packed__))"
