[package]
name = "dynamips-c-unstable"
description = "dynamips-c with USE_UNSTABLE (staticlib)"
edition = "2021"
publish = false
workspace = ".."
version.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
dynamips-c = { path = "../dynamips-c", features = ["USE_UNSTABLE"] }
